package com.fwantastic.librarymanagement.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fwantastic.librarymanagement.model.converter.InstantTypeConverter;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// validates if the table exists or not. table must be created beforehand
@DynamoDBTable(tableName = "book")
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder(toBuilder = true)
public class Book {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  private String title;

  @DynamoDBAttribute
  private int rating;

  @DynamoDBAttribute
  private String author;

  @DynamoDBAttribute
  /**
   * Instant is not supported type.
   * Converter class will automatically convert Instant to string
   * before saving and after retrieving from dynamodb
   */
  @DynamoDBTypeConverted(converter = InstantTypeConverter.class)
  private Instant lastModificationDate;
}
